spring.application.name=proyecto-crud


spring.devtools.add-properties=true
logging.level.web=DEBUG
## Configuracion del puerto
server.port=4000

## Configuracion de logs
logging.level.root=INFO
logging.level.mx.com.gm=DEBUG
logging.pattern.dateformat=hh:mm
spring.main.banner-mode=log
spring.thymeleaf.cache=false
